### ISSUE TITLE
The CLI can not handle relative path on Windows

### ISSUE THREAD

**Issue by thanhminhmr** [thanhminhmr/srx#3]
To quote joerg from encode.su:
`the commandline can not handle relative pathnames like "..\BACKUP_TEMP\BACKUP.DAT"`
https://encode.su/threads/4038-SRX-fast-multi-threaded-SR-compressor?p=78974&viewfull=1#post78974

**Comment by mitiko** [comment]
Have you tested it on Linux?
I checked and I'm using `PathBuf` in my compressor, could be the issue.

**Comment by thanhminhmr** [comment]
Just ran a quick test on my Linux machine, it can handle `srx c ../a/b.dat b.dat.srx` just fine. I'll test it on Windows, maybe it is OS specific.

**Comment by thanhminhmr** [comment]
I cannot reproduce this bug on my Windows machine.
@mitiko Can you reproduce the bug?

**Comment by mitiko** [comment]
I also cannot. Tested it on a 64-bit Windows 10 machine in Azure:

![screenshot-srx-test-vm](https://user-images.githubusercontent.com/26521741/235314078-707cdc16-12a4-4199-9514-e0198c5764d5.png)

**Comment by thanhminhmr** [comment]
Closed as "Cannot reproduce"
